REVOKE ALL ON DATABASE :my_db FROM PUBLIC;

GRANT CONNECT ON DATABASE :my_db TO master;
GRANT TEMPORARY ON DATABASE :my_db TO master;
GRANT CREATE ON DATABASE :my_db TO master;

GRANT CONNECT ON DATABASE :my_db TO rw;
GRANT TEMPORARY ON DATABASE :my_db TO rw;
