REVOKE ALL ON DATABASE :my_db FROM PUBLIC;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;

GRANT CONNECT ON DATABASE :my_db TO master;

GRANT TEMPORARY ON DATABASE :my_db TO master;

GRANT CONNECT ON DATABASE :my_db TO rw;

GRANT TEMPORARY ON DATABASE :my_db TO rw;
