-- revoke public
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

-- master
ALTER SCHEMA public
    OWNER TO master;
GRANT
    USAGE,
    CREATE
    ON SCHEMA public TO master;
GRANT 
    SELECT, 
    INSERT, 
    UPDATE, 
    DELETE
    ON ALL TABLES IN SCHEMA public TO master;
GRANT
    ALL
    ON ALL SEQUENCES IN SCHEMA public TO master;

-- rw
GRANT
    USAGE
    ON SCHEMA public TO rw;
GRANT 
    SELECT, 
    INSERT, 
    UPDATE, 
    DELETE
    ON ALL TABLES IN SCHEMA public TO rw;
GRANT
    USAGE,
    SELECT
    ON ALL SEQUENCES IN SCHEMA public TO rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE ON SEQUENCES TO rw;
