#!/bin/sh

# Called by "git push" after it has checked the remote status, but before anything has
# been pushed. If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This hook will prevent unwanted pushes on Stockly's protected branches.

PROTECTED_BRANCHES="master staging"

_remote="$1"
_url="$2"

while read local_ref local_sha remote_ref remote_sha
do
	for branch in ${PROTECTED_BRANCHES}
	do
		if [[ "refs/heads/${branch}" = ${remote_ref} ]]
		then
			echo "You're trying to push on ${branch}. This is not expected to happen in Stockly's normal Git flow." >&2
			echo "If you really want to do this, pass the option \`--no-verify\` to \`git push\`." >&2
			exit 1
		fi
	done
done

exit 0
