1password-secret-keys:
    bebert64: ENC[AES256_GCM,data:4KunP++PgMJZacaYe44dV3uXEk5yl6qlJswnHDMAIWp2JbVwZtWXfA==,iv:IShZCZjceRtfiAFh9an3CrNKpJZmHnQJyGx+YC240Vc=,tag:IcyP6ERdSxjMJEUihc1ySA==,type:str]
    stockly: ENC[AES256_GCM,data:H9HGVls1pQ9PmMsDrrrVIbXyzjgGdpskw188VpQkC9ZKL1tsH6k5og==,iv:Vrg+I/yr0uAJELKn/i0LLYQRszs8KW7tEe3az2Oyi80=,tag:0z0Zm2DtPTdDKo2zxl0RIQ==,type:str]
ffsync:
    bebert64: ENC[AES256_GCM,data:AVSA7/oXUeAp0oZxL3E=,iv:QzUkaDfxh+7DkFW2gJzmXK8H9kB9ouGIXuHCI+qC+Tk=,tag:IbMGOTo+l3IU8yvkYM0pag==,type:str]
    shortcuts-db: ENC[AES256_GCM,data:MH/0kDlFJE1DYubSnYM=,iv:G406usYPbDyIrhPMQVhuM9BMH7frWI7J+vHC9M/At9k=,tag:bSxauPHCLEmUU6YyiSaqRA==,type:str]
raspi:
    postgresql:
        rw: ENC[AES256_GCM,data:u4wXXfZKOTcN/Gxc1ctPQ4o6ok4=,iv:NuiJrUYTyCkcnLZURfPQG4jdC5UVhGt/x7GGGtZnA84=,tag:V+VigAn9eiguwdtJdNevBA==,type:str]
stash:
    api-key: ENC[AES256_GCM,data:WUKRo8guOioQ5YcsXWT/HdNkDpv41CLfohPmceW+/9hmlQtOT09YMzqDiw9THaWPy87E8b/PUS9r6t/3+EPxXMD8Y8CtpmdvaStMp4KSW4Ddun7dI1RLQ+pZXNtVY57FaY4WR5fxs+dbgeCJSyimBT+G4qfsRVzzUmgepkSrs2zezee3EAwqm3zbVzjuT1Bgzpma2hayKX7SqzhjSswPVd2fWjCc+Uc=,iv:pNFV0kRhfwvaiiC4flLmCxKybNmmJIqAjJd0JVX2aFk=,tag:FyfGWQkqkTofc4c7eiFRXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jl54jpg6uk5x3wnjpy4sa5k376yemfal86x085hgzfdmqh4gc99shah24v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaGk4UmJ1U1JRMUZhaGZK
            STVMa2kwa1BoWklpa29CaFVTWEM2Y2JnalNrCnY4ZmVadGw4M0tDMnpNdzNwaHFU
            aUZSMkIxdURQWldzVy9RQXo0RkdVakUKLS0tIFNTd2tTZFVoTmZZTTlnb1lFQ2cx
            VStrNU01VTloTTd2MDRHOC8zQ0x4RTAK7o3fMvQh7bPE2IYekqQe7qYlljoDie8n
            xm+jdTGlTo/l6O3mETU5Xxp/4s3d7Vq9VPbRPDYoRNYda5pJWV/kuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-25T11:11:18Z"
    mac: ENC[AES256_GCM,data:C3XWSzB2wArxTz6fbQkxKgUl5hYCg8tZny9oWoedg2+7TSaExKgGMJNRHCTA9JAlF1rfM0NjM2vRIGDWexPhZQ+SzMp0Axd2VaCXsNw3PqVQd0/qwZmx7DB5Ur0/u1ArYzppFD2XBH9wBGYn1//S16xMKyK7h+ROj/VDEfA2NOE=,iv:/wWnfOjhoEDeumI84GHNzLAFbuzFuhKmuPMOQ+qgf6c=,tag:RoBKmryN3QZb9X+UEhEDvA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
