include $(shell git rev-parse --show-toplevel)/mkFiles/packages/base.mk

install:
	@echo "Nothing to do"

build: install

clean:
	@echo "Nothing to do"

lint:
	@echo "Nothing to do"

autofix:
	@echo "Nothing to do"

tunits:
	@echo "Nothing to do"
