{
  imports = [
    ./common.nix
    ./configs/conky
    ./configs/cursor
    ./configs/datagrip
    ./configs/ferdium
    ./configs/mpc-qt
    ./configs/picom
    ./configs/polybar
    ./configs/music
    ./configs/sqlfluff
    ./configs/terminal
    ./configs/autorandr.nix
    ./configs/avidemux.nix
    ./configs/calculator.nix
    ./configs/firefox.nix
    ./configs/flameshot.nix
    ./configs/i3.nix
    ./configs/insomnia.nix
    ./configs/lock.nix
    ./configs/rofi.nix
    ./configs/slack.nix
    ./configs/theme.nix
    ./configs/udiskie.nix
    ./configs/vdhcoapp.nix
  ];
}
