api_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJzaG9ydGN1dHMuZGJAZ21haWwuY29tIiwiaWF0IjoxNjc4NzIzMzY4LCJzdWIiOiJBUElLZXkifQ.hhf_vN_o3uuT3d9rnAmjTJGXaeoQ0ZjM1oKcRZEVOaI
blobs_path: /usr/local/etc/stash/data
blobs_storage: FILESYSTEM
calculate_md5: false
create_image_clip_from_videos: false
dangerous_allow_public_without_auth: "false"
database: /usr/local/etc/stash/stash-go.sqlite
defaults:
  auto_tag_task:
    paths: []
    performers:
    - '*'
    studios: []
    tags: []
  generate_task:
    markerids: []
    markers: false
    phashes: true
    previewoptions:
      previewexcludeend: "0"
      previewexcludestart: "0"
      previewpreset: slow
      previewsegmentduration: 0.75
      previewsegments: 12
    previews: true
    sceneids: []
    sprites: false
  identify_task:
    options:
      fieldoptions:
      - createmissing: false
        field: title
        strategy: OVERWRITE
      - createmissing: false
        field: code
        strategy: OVERWRITE
      - createmissing: true
        field: studio
        strategy: OVERWRITE
      - createmissing: true
        field: performers
        strategy: MERGE
      - createmissing: false
        field: tags
        strategy: IGNORE
      - createmissing: false
        field: details
        strategy: MERGE
      includemaleperformers: true
      setcoverimage: true
      setorganized: true
    paths: []
    sceneids: []
    sources:
    - options: null
      source:
        scraperid: null
        stashboxendpoint: https://stashdb.org/graphql
        stashboxindex: null
    - options:
        fieldoptions:
        - createmissing: null
          field: studio
          strategy: MERGE
        - createmissing: null
          field: performers
          strategy: MERGE
        - createmissing: null
          field: stash_ids
          strategy: MERGE
        - createmissing: null
          field: tags
          strategy: IGNORE
        includemaleperformers: null
        setcoverimage: null
        setorganized: null
      source:
        scraperid: Pornhub
        stashboxendpoint: null
        stashboxindex: null
    - options:
        fieldoptions:
        - createmissing: null
          field: stash_ids
          strategy: MERGE
        includemaleperformers: null
        setcoverimage: null
        setorganized: null
      source:
        scraperid: ThePornDB
        stashboxendpoint: null
        stashboxindex: null
  scan_task:
    usefilemetadata: false
    stripfileextension: false
    scangeneratecovers: true
    scangeneratepreviews: true
    scangenerateimagepreviews: false
    scangeneratesprites: false
    scangeneratephashes: true
    scangeneratethumbnails: false
    scangenerateclippreviews: false
exclude:
- .* - intro.*
gallery_cover_regex: (poster|cover|folder|board)\.[^\.]+$
generated: /usr/local/etc/stash/generated
host: 0.0.0.0
jwt_secret_key: 0029b60e04c1ab38eceb91799c94b6f664caace568be80ccd8a50c0fa015fdd0
no_proxy: localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
nobrowser: false
notifications_enabled: true
parallel_tasks: 1
password: $2a$04$9kj7G2071akbRba.G9m2F.Rl0FuQ4CY7bqlTWSgtm8n6Or6obi0LO
plugins_path: /usr/local/etc/stash/plugins
port: 9999
preview_audio: true
preview_exclude_end: "0"
preview_exclude_start: "0"
preview_segment_duration: 0.75
preview_segments: 12
scraper_exclude_tag_patterns:
- .*
scrapers_path: /usr/local/etc/stash/scrapers
security_tripwire_accessed_from_public_internet: ""
sequential_scanning: false
session_store_key: d15fcbf5457be122589cd9a5fa15925a93b5cbc67c898a6334efa4cbeb7f3d63
show_one_time_moved_notification: false
sound_on_preview: false
stash:
- excludeimage: true
  excludevideo: false
  path: /mnt/NAS/Comics/Fini/Planet of the Apes/14 Planet of the Apes issues/Elseworlds/Videos
    a couper
- excludeimage: true
  excludevideo: false
  path: /mnt/NAS/Comics/Fini/Planet of the Apes/14 Planet of the Apes issues/Elseworlds/Videos
    cut
stash_boxes:
- apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhN2ZkYjAxNS0xMjdhLTRkYjQtOThjNy1mMzk4MTVhZjQ2MDQiLCJzdWIiOiJBUElLZXkiLCJpYXQiOjE2NzcyMzkxMzR9.6KZgPp_nS0GzybDsbUsKggvgXYZoFjzwCmDyvtBmQb8
  endpoint: https://stashdb.org/graphql
  name: stash_db
theme_color: '#202b33'
ui:
  front_page_content:
  - __typename: CustomFilter
    direction: DESC
    message:
      id: recently_released_objects
      values:
        objects: Scenes
    mode: SCENES
    sortBy: date
  - __typename: CustomFilter
    direction: DESC
    message:
      id: recently_added_objects
      values:
        objects: Studios
    mode: STUDIOS
    sortBy: created_at
  - __typename: CustomFilter
    direction: DESC
    message:
      id: recently_released_objects
      values:
        objects: Movies
    mode: MOVIES
    sortBy: date
  - __typename: CustomFilter
    direction: DESC
    message:
      id: recently_added_objects
      values:
        objects: Performers
    mode: PERFORMERS
    sortBy: created_at
  - __typename: CustomFilter
    direction: DESC
    message:
      id: recently_released_objects
      values:
        objects: Galleries
    mode: GALLERIES
    sortBy: date
  last_note_seen: 20230301
username: shortcuts.db@gmail.com
video_file_naming_algorithm: OSHASH
write_image_thumbnails: true
